### ISSUE TITLE
Problem with admin dashboard user Interface in development branch

### ISSUE THREAD

**Issue by loudiman** [loudiman/Exit-Interview-Question#19]
The navigation bar is not appropriate loading but in the previous commit it works properly, that is,

commit cf2d6d85c226b8a2af199af8be8277dc2a095ec2 (HEAD -> development)
Merge: 4ca185d 8d0ce2c
Author: Lou Diamond T. Morados <83881490+loudiman@users.noreply.github.com>
Date:   Mon Dec 9 03:33:33 2024 +0800
Merge pull request #13 from loudiman/merger/main-geo-lenar-marven
Merger/main geo lenar marven

**Comment by VladTemp27** [comment]
![image](https://github.com/user-attachments/assets/b322aecf-6c96-47e4-b854-b773dcf129b6)

nav-bar and side-bar was nav_bar and side_bar thus the css was not applying
